SELECT TOP (1000) [Ticket_ID]
      ,[Customer_Name]
      ,[Customer_Email]
      ,[Customer_Age]
      ,[Customer_Gender]
      ,[Product_Purchased]
      ,[Date_of_Purchase]
      ,[Ticket_Type]
      ,[Ticket_Subject]
      ,[Ticket_Description]
      ,[Ticket_Status]
      ,[Resolution]
      ,[Ticket_Priority]
      ,[Ticket_Channel]
      ,[First_Response_Time]
      ,[Time_to_Resolution]
      ,[Customer_Satisfaction_Rating]
  FROM [dbo].[customer_support_tickets csv]
  select avg(Customer_Satisfaction_Rating) as CSAT,Ticket_Priority,Ticket_Channel from [customer_support_tickets csv] group by Ticket_Priority,Ticket_Channel order by avg(Customer_Satisfaction_Rating) desc
 